Timeseries...

#Notes on analysis.
#Instead of having (x,y) pairs, we have an ordered set. 
#y1919-y2017
#The prediction asks what y2018, y2019, y 2019 is going to be.
#This looks more like a series! This is because everything continues.
#We want to make a prediction of the series we do not know by using known values.

#important points
##Relationship is never causal. Each year does not cause anything. Categorial Correlation
#Using the correlation to make a predition.
#Is the past predictive of the future?  ie. Are the policies and behaviors still the same?



#additve --> linear relationship. things get added.
#multiplicative --> curvature
##Do a log transformation. Undoes a multiplicative effect and make it additive.
### This graph is multiplicative because we didn't earn more on top of before
####growth must increase by a percentage, a compounded rate not by an additive flat rate.
####We undo the log after analysis.
#### The recent past is only relevant!!





#Modify Data
##Log transformation
##filter to most recent past


#To extrapolate
#condition on yt
#yt = last observed value
#IF 2018 was just like last year, we would like to add some mean change from year to year.
##E(yt+1|yt)
#Take every observation and make a projection

#We don't want to only 
#We want the model to recognize the correlation within {yt} -->embedded correlation.
##"Short memory"
##"Long memory"
#NO cross correlation. though there might be..
#Simple time series. AR,I,MA(1,1,1) 
#######--> mean(mu) + phi + SigmaEpsilont+1 + sigma epsilont
####### where epsilon t are iid N(0,sigma^2) <- white noise.



#I >>>>> (yt+1) - (yt) change year to year.                           future difference
##That change on average has a mean mu. 
#AR >>>> phi(yt-yt-1) the last period's change. Long Memory           past difference
#epsilont+1 Short Memory
#Sigma epsilont



#Estimation is by likelihood, so check for convergence.
#SAS -> proc arima;
#R library(astsa)
#Code:
### estimate ARIMA(1,1,1) parameters and standard errors
#(mu,phi,theta)
#Predict using the estimated model and prediction intervals
#Yet estimates are in the log scale, so we need to untransform the data.


#ARIMA model assumptions!!
1.There are no known/suspected predictor variables
2.There are no level shifts
3.There are no deterministic time trends of the form 1,2,3,...,t1,2,3,...,t
4.There are no seasonal dummies
5.There are no one time anomalies
6.The model parameters are constant over time
7.The error process is homoscedastic (constant) over time

#install.packages("devtools")
#devtools::install_github("nickpoison/astsa")
#library("astsa", lib.loc="~/Library/R/3.4/library")


```{r}
sarima(x,1,1,1)
sarima.for(x,n.ahead=5,1,1,1)
```

         Estimate     SE t.value p.value
ar1       -0.0074 0.4917 -0.0151  0.9880
ma1       -0.1765 0.4812 -0.3669  0.7149
constant   0.0388 0.0070  5.5730  0.0000


ar1 is phi hat
ma1 is epsilon hat
constant is mu hat

*######################################################################################################*
Seasonal Time Series


Periodical monthly data

{yt}
y1 = jan 1991
y2 = feb 1991
.
.
.
y12 = dec 1991
y13 = Jan 1992
...

MORE DATA = more detail inside, not more years. 
#Problem with daily data = leap years. So don't worry about it.



notation:
ARIMA (1,1,1)       X             (1,1,1)sub12
^month to month piece             ^year to year
jan predicts feb                  1991 predicts 1992
feb predicts mar                  1992 predicts 1993

same time series predictability as before, but skip 12 months and see what happens.

monthly ar1
lowercase phi
monthly ma1
lowercase theta


seasonal ar1
uppercase phi
seasonal ma1
uppercase phi


*estimate by maximum likelihood*
*mu gets subtracted away from seasonal differences*

pseudo code:
1.get data
2.subset data to recent past *filtering*
- additive model -> do we need to transform?
- no outliers -> EDA
3.model features
- fit model arima(1,1,1)x(1,1,1)12
4. predictions/forecasts for 2 years
-24 months
-oct,nov,dec2017 + 2018 and 2019
  -27 months
5. prediction + 95% prediction intervals
6. Pretty graph

